'use strict';

const players = [
  {name: '小笠原　慎之介', number: 11},
  {name: '田島　慎二', number: 12},
  {name: '橋本　侑樹', number: 13},
  {name: '谷元　圭介', number: 14},
  {name: '又吉　克樹', number: 16},
  {name: '柳　裕也', number: 17},
  {name: '吉見　一起', number: 19},
  {name: '岡田　俊哉', number: 21},
  {name: '大野　雄大', number: 22},
  {name: '福谷　浩司', number: 24},
  {name: '佐藤　優', number: 25},
  {name: '梅津　晃大', number: 28},
  {name: '山井　大介', number: 29},
  {name: '阿知羅　拓馬', number: 30},
  {name: '祖父江　大輔', number: 33},
  {name: '福　敬登', number: 34},
  {name: '岡野　祐一郎', number: 36},
  {name: '松葉　貴大', number: 38},
  {name: '石川　翔', number: 40},
  {name: '勝野　昌慶', number: 41},
  {name: '三ツ間　卓也', number: 43},
  {name: '鈴木　博志', number: 46},
  {name: '笠原　祥太郎', number: 47},
  {name: '清水　達也', number: 50},
  {name: 'ゴンザレス', number: 53},
  {name: '藤嶋　健人', number: 54},
  {name: '山本　拓実', number: 59},
  {name: '垣越　建伸', number: 61},
  {name: '竹内　龍臣', number: 62},
  {name: '小熊　凌佑', number: 64},
  {name: '伊藤　準規', number: 65},
  {name: '濱田　達郎', number: 69},
  {name: 'ロメロ', number: 70},
  {name: 'R. マルティネス', number: 97},
  {name: '木下　雄介', number: 98},
  {name: '鈴木　翔太', number: 99},
  {name: '大野　奨太', number: 27},
  {name: '木下　拓哉', number: 35},
  {name: '郡司　裕也', number: 44},
  {name: '加藤　匠馬', number: 52},
  {name: '石橋　康太', number: 58},
  {name: '桂　依央利', number: 68},
  {name: '高松　渡', number: 0},
  {name: '京田　陽太', number: 1},
  {name: '石川　昂弥', number: 2},
  {name: '高橋　周平', number: 3},
  {name: '阿部　寿樹', number: 5},
  {name: '根尾　昂', number: 7},
  {name: '石川　駿', number: 9},
  {name: '石垣　雅海', number: 32},
  {name: '三ツ俣　大樹', number: 37},
  {name: '溝脇　隼人', number: 48},
  {name: '福田　永将', number: 55},
  {name: '堂上　直倫', number: 63},
  {name: 'ビシエド', number: 66},
  {name: '藤井　淳志', number: 4},
  {name: '平田　良介', number: 6},
  {name: '大島　洋平', number: 8},
  {name: '遠藤　一星', number: 23},
  {name: '井領　雅貴', number: 26},
  {name: '渡辺　勝', number: 31},
  {name: 'アルモンテ', number: 42},
  {name: 'シエラ', number: 45},
  {name: '伊藤　康祐', number: 49},
  {name: '滝野　要', number: 51},
  {name: '武田　健吾', number: 56},
  {name: '岡林　勇希', number: 60},
];